name: dhapi-automation-buy

on:
  schedule:
    - cron: '45 09 * * 6'

jobs:
  dhapi-automation-buy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup credential
        env:
          DHAPI_USERNAME: ${{ secrets.DHAPI_USERNAME }}
          DHAPI_PASSWORD: ${{ secrets.DHAPI_PASSWORD }}
        run: |
          mkdir -p ~/.dhapi
          echo "[default]" > ~/.dhapi/credentials
          echo "username = \"$DHAPI_USERNAME\"" >> ~/.dhapi/credentials
          echo "password = \"$DHAPI_PASSWORD\"" >> ~/.dhapi/credentials
      - name: Setup python
        id: dhapi
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt
      - name: Buy
        id: dhapi_buy
        run: |
          {
            echo "BUY<<EOF"
            python buyer.py buy
            echo EOF
          } >> $GITHUB_OUTPUT
      - name: Send result
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: "${{ steps.dhapi_buy.outputs.BUY }}"
